#!/usr/bin/env node
const https = require('https');
const http  = require('http');
const fs    = require('fs');
const path  = require('path');

const FONTS = [
  { url: 'https://cdn.jsdelivr.net/gh/googlefonts/noto-fonts@main/hinted/ttf/NotoSans/NotoSans-Regular.ttf', name: 'regular' },
  { url: 'https://cdn.jsdelivr.net/gh/googlefonts/noto-fonts@main/hinted/ttf/NotoSans/NotoSans-Bold.ttf',    name: 'bold'    },
];

function download(url) {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http;
    client.get(url, (res) => {
      if (res.statusCode === 301 || res.statusCode === 302) {
        return download(res.headers.location).then(resolve).catch(reject);
      }
      if (res.statusCode !== 200) { reject(new Error(`HTTP ${res.statusCode} for ${url}`)); return; }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => {
        const buf = Buffer.concat(chunks);
        if (buf.length < 50000) { reject(new Error(`Font too small: ${buf.length} bytes`)); return; }
        console.log(`  ✓ ${url.split('/').pop()} (${Math.round(buf.length/1024)} KB)`);
        resolve(buf);
      });
      res.on('error', reject);
    }).on('error', reject);
  });
}

async function main() {
  console.log('Downloading fonts...');
  const bufs = {};
  for (const f of FONTS) {
    bufs[f.name] = await download(f.url);
  }

  // Generate TypeScript module with fonts embedded as base64
  const outDir = path.join(__dirname, '..', 'lib');
  fs.mkdirSync(outDir, { recursive: true });
  const out = path.join(outDir, 'fonts-data.ts');
  const content = `// AUTO-GENERATED by scripts/download-fonts.js - do not edit manually
const NOTO_REGULAR_B64 = '${bufs.regular.toString('base64')}';
const NOTO_BOLD_B64 = '${bufs.bold.toString('base64')}';
export const NOTO_REGULAR: Buffer = Buffer.from(NOTO_REGULAR_B64, 'base64');
export const NOTO_BOLD: Buffer = Buffer.from(NOTO_BOLD_B64, 'base64');
`;
  fs.writeFileSync(out, content, 'utf8');
  console.log(`  ✓ lib/fonts-data.ts generated (${Math.round(content.length/1024)} KB)`);
  console.log('Fonts ready.');
}
main().catch(e => { console.error('Font error:', e.message); process.exit(1); });
